name: Carlos Rodrigues
description: Machine and Deep Learning

menu-en:
  home: index
  about me: about
  blog: blog
  curriculum vitae: http://lattes.cnpq.br/0176590198026811

menu-pt:
  home: index
  sobre mim: about
  blog: blog
  curriculum vitae: http://lattes.cnpq.br/0176590198026811