name: Carlos Rodrigues
description: Machine and Deep Learning

menu:
  home: index
  about me: about
  blog: blog
  curriculum vitae: http://lattes.cnpq.br/0176590198026811

about-page:
  name: Carlos Rodrigues
  short_biography: PhD Candidate at Stanford University
  user_info:
    - title: Location
      content: "Rio Grande, RS, BR"
    - title: "Twitter"
      link: "https://twitter.com/cerfdotdev"
    - title: "LinkedIn"
      link: "https://www.linkedin.com/in/carlsrodrigues/"
    - title: "GitHub"
      link: "https://github.com/carls-rodrigues"
    - title: GitLab
      link: "https://gitlab.com/carlsrodrigues"
    - title: Google Scholar
      link: "https://scholar.google.com/citations?user=kGIEiPcAAAAJ&hl=en"
    
  education: 
    - title: Master's Degree in Computer Science, Federal University of Rio Grande, 2017-2019
      bullets: [Developed machine learning models, Conducted data analysis, Developed data pipelines]
    - title: Bachelor's Degree in Computer Science, Federal University of Rio Grande, 2013-2017
      bullets: [Developed machine learning models, Conducted data analysis, Developed data pipelines]
  experience:
    - title: Machine Learning Engineer, Google, 2019-2020
      bullets: [Developed machine learning models, Conducted data analysis, Developed data pipelines]
    - title: Data Scientist, Facebook, 2018-2019
      bullets: [Developed machine learning models, Conducted data analysis, Developed data pipelines]
  publications:
    - title: "Ph.D in Computer Science, Stanford University, Sept 2018"
      bullets: ["Colin Wei, Kendrick Shen, Yining Chen, Tengyu Ma", "Manuscript arXiv:2010.03622"]
  awards: 
    - title: "Outstanding Researcher Award"
      bullets: 
        - "Organization: Academic Society XYZ, Year: 2019"
    - title: "Best Paper Award"
      bullets: 
        - "Conference: International Conference on Data Science, Year: 2018"
  teaching: 
    - title: "Teaching Assistant"
      bullets: 
        - "Course: Introduction to Machine Learning, Institution: University ABC, Year: 2021"
    - title: "Guest Lecturer"
      bullets: 
        - "Course: Deep Learning Applications, Institution: College XYZ, Year: 2020"
  service_and_leadership: 
    - title: "Reviewer"
      bullets: 
        - "Journal: Journal of Data Science, Year: 2022"
    - title: "Conference Volunteer"
      bullets: 
        - "Conference: Conference on Artificial Intelligence, Year: 2021"
  skills: 
    - title: "Programming Languages"
      bullets: 
        - "Python, R"
    - title: "Machine Learning Frameworks"
      bullets: 
        - "Pytorch, Tensorflow, Spark"
  